<?php
return array (
  'position' => 
  array (
    'fieldid' => '397',
    'modelid' => '10',
    'siteid' => '0',
    'field' => 'position',
    'name' => '职位',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'linkage',
    'setting' => '{"linkageid":"3360","showtype":"0","space":""}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'linkageid' => '3360',
    'showtype' => '0',
    'space' => '',
  ),
  'dept' => 
  array (
    'fieldid' => '494',
    'modelid' => '10',
    'siteid' => '0',
    'field' => 'dept',
    'name' => '处室',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'linkage',
    'setting' => '{"linkageid":"3376","showtype":"0","space":""}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'linkageid' => '3376',
    'showtype' => '0',
    'space' => '',
  ),
  'leib' => 
  array (
    'fieldid' => '520',
    'modelid' => '10',
    'siteid' => '0',
    'field' => 'leib',
    'name' => '通知查看权限',
    'tips' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => '{"options":"\\u6240\\u6709\\u4eba|1\\r\\n\\u9886\\u5bfc|2\\r\\n\\u5904\\u5ba4\\u8d1f\\u8d23\\u4eba|3","boxtype":"checkbox","fieldtype":"varchar","minnumber":"1","width":"100","size":"1","defaultvalue":"1","outputtype":"1"}',
    'formattribute' => '',
    'unsetgroupids' => '',
    'unsetroleids' => '',
    'iscore' => '0',
    'issystem' => '0',
    'isunique' => '0',
    'isbase' => '1',
    'issearch' => '0',
    'isadd' => '0',
    'isfulltext' => '0',
    'isposition' => '0',
    'listorder' => '0',
    'disabled' => '0',
    'isomnipotent' => '0',
    'options' => '所有人|1
领导|2
处室负责人|3',
    'boxtype' => 'checkbox',
    'fieldtype' => 'varchar',
    'minnumber' => '1',
    'width' => '100',
    'size' => '1',
    'defaultvalue' => '1',
    'outputtype' => '1',
  ),
);
?>