<?php
return array (
  'title' => '职位',
  'style' => '0',
  'siteid' => '0',
  'data' => 
  array (
    3361 => 
    array (
      'linkageid' => '3361',
      'name' => '局长',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3362 => 
    array (
      'linkageid' => '3362',
      'name' => '党委书记',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3363 => 
    array (
      'linkageid' => '3363',
      'name' => '副局长',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3364 => 
    array (
      'linkageid' => '3364',
      'name' => '副巡视员',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3365 => 
    array (
      'linkageid' => '3365',
      'name' => '处长',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3366 => 
    array (
      'linkageid' => '3366',
      'name' => '副处长',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3367 => 
    array (
      'linkageid' => '3367',
      'name' => '主任',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3368 => 
    array (
      'linkageid' => '3368',
      'name' => '副主任',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3369 => 
    array (
      'linkageid' => '3369',
      'name' => '副调研员',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3370 => 
    array (
      'linkageid' => '3370',
      'name' => '主任科员',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3371 => 
    array (
      'linkageid' => '3371',
      'name' => '调研员',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3372 => 
    array (
      'linkageid' => '3372',
      'name' => '副主任科员',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3373 => 
    array (
      'linkageid' => '3373',
      'name' => '办事员',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3374 => 
    array (
      'linkageid' => '3374',
      'name' => '其它',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
    3375 => 
    array (
      'linkageid' => '3375',
      'name' => '科员',
      'style' => '',
      'parentid' => '0',
      'child' => '0',
      'arrchildid' => '',
      'keyid' => '3360',
      'listorder' => '0',
      'description' => '',
      'setting' => NULL,
      'siteid' => '0',
    ),
  ),
);
?>