DROP TABLE IF EXISTS `v9_ren`;
CREATE TABLE IF NOT EXISTS `v9_ren` (
  `id` smallint(5) NOT NULL AUTO_INCREMENT,
  `siteid` smallint(4) NOT NULL DEFAULT 1,
  `name` varchar(30) NOT NULL COMMENT '姓名',
  `nation` varchar(30) NOT NULL COMMENT '民族',
  `sfz` varchar(30) NOT NULL COMMENT '身份证号',
  `jg` varchar(255) NOT NULL,
  `address` varchar(255) NOT NULL COMMENT '家庭住址',
  `hksz` varchar(255) NOT NULL COMMENT '户口所在地',
  `dpcs` varchar(255) NOT NULL COMMENT '地派出所',
  `phone` varchar(255) NOT NULL COMMENT '联系电话',
  `lxdz` varchar(255) NOT NULL COMMENT '联系地址',
  `rdtime` varchar(255) NOT NULL COMMENT '入党日期',
  `ltxtime` varchar(255) NOT NULL COMMENT '离退休时间',
  `ltxdw` varchar(255) NOT NULL COMMENT '离退休时单位',
  `fgcs` varchar(255) NOT NULL COMMENT '分管处室',
  `dy` varchar(255) NOT NULL COMMENT '现享受的待遇',
  `education` varchar(255) NOT NULL COMMENT '文化程度',
  `wgqz` varchar(255) NOT NULL COMMENT '文革前曾',
  `zgzw` varchar(255) NOT NULL COMMENT '任最高职位',
  `zyjszw` varchar(255) NOT NULL COMMENT '专业技术职位',
  `dnzw` varchar(255) NOT NULL COMMENT '党内职务',
  `dah` varchar(255) NOT NULL COMMENT '档案号',
  `bz` varchar(255) NOT NULL COMMENT '备注',
  `sex` varchar(255) NOT NULL COMMENT '行别',
  `csrq` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '出生日期',
  `zzmm` varchar(255) NOT NULL COMMENT '政治面貌',
  `cjgm` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '参加革命时间',
  `zhtime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '转正日期',
  `tgltime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '退改离时间',
  `lxzw` varchar(255) NOT NULL COMMENT '离休职务',
  `pztime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00' COMMENT '批准时间',
  `zj` varchar(255) NOT NULL COMMENT '职级',
  `zyzwjb` varchar(255) NOT NULL COMMENT '专业职务级别',
  `xszdzb` varchar(255) NOT NULL COMMENT '现所在党支部',
  `isdie` varchar(255) NOT NULL COMMENT '是否死亡',
  `pic` varchar(255) NOT NULL COMMENT '照片',
  `zw` varchar(255) NOT NULL COMMENT '职务',
  `gzsj` varchar(255) NOT NULL COMMENT '工作时间',
  `drjnsj` varchar(255) NOT NULL COMMENT '调入局内时间',
  `ydw` varchar(255) NOT NULL COMMENT '原单位',
  `jl` varchar(255) NOT NULL COMMENT '简历',
  `addtime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `edittime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM;
