<?php
return array (
  142 => 
  array (
    'modelid' => '142',
    'siteid' => '1',
    'name' => '人员管理',
    'description' => '人员管理',
    'tablename' => 'uinfo',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '1',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'js_template' => '',
    'admin_list_template' => 'people_list_tx',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '3',
  ),
  143 => 
  array (
    'modelid' => '143',
    'siteid' => '1',
    'name' => '住院信息管理',
    'description' => '住院信息管理',
    'tablename' => 'zyinfo',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'js_template' => '',
    'admin_list_template' => 'people_list_zhuyuan',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '3',
  ),
  141 => 
  array (
    'modelid' => '141',
    'siteid' => '1',
    'name' => '健康档案信息',
    'description' => '健康档案',
    'tablename' => 'dangan',
    'setting' => '',
    'addtime' => '0',
    'items' => '0',
    'enablesearch' => '1',
    'disabled' => '0',
    'default_style' => 'default',
    'category_template' => 'category',
    'list_template' => 'list',
    'show_template' => 'show',
    'js_template' => '',
    'admin_list_template' => 'people_list_dangan',
    'member_add_template' => '',
    'member_list_template' => '',
    'sort' => '0',
    'type' => '3',
  ),
);
?>